name: CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: "TEST_KEY"  # Dummy: lets Streamlit boot for smoke-test

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8

      - name: Lint code
        run: flake8 . --max-line-length 120

      - name: Smoke-test Streamlit app
        run: |
          nohup streamlit run app.py --server.port 8501 &> /dev/null &
          sleep 10
          curl --fail http://localhost:8501 \
            || { echo "App failed to start"; exit 1; }
